// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/raft_transport.proto

package rafttransportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // gogo-marshaled raftpb.Message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_proto_raft_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_proto_raft_transport_proto_rawDescGZIP(), []int{0}
}

func (x *RaftMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RaftMessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessageAck) Reset() {
	*x = RaftMessageAck{}
	mi := &file_proto_raft_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessageAck) ProtoMessage() {}

func (x *RaftMessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessageAck.ProtoReflect.Descriptor instead.
func (*RaftMessageAck) Descriptor() ([]byte, []int) {
	return file_proto_raft_transport_proto_rawDescGZIP(), []int{1}
}

var File_proto_raft_transport_proto protoreflect.FileDescriptor

const file_proto_raft_transport_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/raft_transport.proto\x12\x0frafttransportpb\"!\n" +
	"\vRaftMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x10\n" +
	"\x0eRaftMessageAck2V\n" +
	"\rRaftTransport\x12E\n" +
	"\x04Send\x12\x1c.rafttransportpb.RaftMessage\x1a\x1f.rafttransportpb.RaftMessageAckB8Z6github.com/carissaayo/go-kv-dist/proto/rafttransportpbb\x06proto3"

var (
	file_proto_raft_transport_proto_rawDescOnce sync.Once
	file_proto_raft_transport_proto_rawDescData []byte
)

func file_proto_raft_transport_proto_rawDescGZIP() []byte {
	file_proto_raft_transport_proto_rawDescOnce.Do(func() {
		file_proto_raft_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_raft_transport_proto_rawDesc), len(file_proto_raft_transport_proto_rawDesc)))
	})
	return file_proto_raft_transport_proto_rawDescData
}

var file_proto_raft_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_raft_transport_proto_goTypes = []any{
	(*RaftMessage)(nil),    // 0: rafttransportpb.RaftMessage
	(*RaftMessageAck)(nil), // 1: rafttransportpb.RaftMessageAck
}
var file_proto_raft_transport_proto_depIdxs = []int32{
	0, // 0: rafttransportpb.RaftTransport.Send:input_type -> rafttransportpb.RaftMessage
	1, // 1: rafttransportpb.RaftTransport.Send:output_type -> rafttransportpb.RaftMessageAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_raft_transport_proto_init() }
func file_proto_raft_transport_proto_init() {
	if File_proto_raft_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_raft_transport_proto_rawDesc), len(file_proto_raft_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_raft_transport_proto_goTypes,
		DependencyIndexes: file_proto_raft_transport_proto_depIdxs,
		MessageInfos:      file_proto_raft_transport_proto_msgTypes,
	}.Build()
	File_proto_raft_transport_proto = out.File
	file_proto_raft_transport_proto_goTypes = nil
	file_proto_raft_transport_proto_depIdxs = nil
}
